//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Internet_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Адрес.
    /// </summary>
    // *** Start programmer edit section *** (Адрес CustomAttributes)

    // *** End programmer edit section *** (Адрес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АдресE", new string[] {
            "Улица as \'Улица\'",
            "Город as \'Город\'",
            "КодАдреса as \'Код адреса\'",
            "КодКлиента as \'Код клиента\'",
            "Индекс as \'Индекс\'"})]
    [View("АдресL", new string[] {
            "Улица as \'Улица\'",
            "Город as \'Город\'",
            "КодАдреса as \'Код адреса\'",
            "КодКлиента as \'Код клиента\'",
            "Индекс as \'Индекс\'"})]
    public class Адрес : ICSSoft.STORMNET.DataObject
    {
        
        private string fУлица;
        
        private string fГород;
        
        private int fКодАдреса;
        
        private int fКодКлиента;
        
        private int fИндекс;
        
        // *** Start programmer edit section *** (Адрес CustomMembers)

        // *** End programmer edit section *** (Адрес CustomMembers)

        
        /// <summary>
        /// Город.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.Город CustomAttributes)

        // *** End programmer edit section *** (Адрес.Город CustomAttributes)
        [StrLen(255)]
        public virtual string Город
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.Город Get start)

                // *** End programmer edit section *** (Адрес.Город Get start)
                string result = this.fГород;
                // *** Start programmer edit section *** (Адрес.Город Get end)

                // *** End programmer edit section *** (Адрес.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.Город Set start)

                // *** End programmer edit section *** (Адрес.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Адрес.Город Set end)

                // *** End programmer edit section *** (Адрес.Город Set end)
            }
        }
        
        /// <summary>
        /// Индекс.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.Индекс CustomAttributes)

        // *** End programmer edit section *** (Адрес.Индекс CustomAttributes)
        public virtual int Индекс
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.Индекс Get start)

                // *** End programmer edit section *** (Адрес.Индекс Get start)
                int result = this.fИндекс;
                // *** Start programmer edit section *** (Адрес.Индекс Get end)

                // *** End programmer edit section *** (Адрес.Индекс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.Индекс Set start)

                // *** End programmer edit section *** (Адрес.Индекс Set start)
                this.fИндекс = value;
                // *** Start programmer edit section *** (Адрес.Индекс Set end)

                // *** End programmer edit section *** (Адрес.Индекс Set end)
            }
        }
        
        /// <summary>
        /// КодАдреса.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.КодАдреса CustomAttributes)

        // *** End programmer edit section *** (Адрес.КодАдреса CustomAttributes)
        public virtual int КодАдреса
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.КодАдреса Get start)

                // *** End programmer edit section *** (Адрес.КодАдреса Get start)
                int result = this.fКодАдреса;
                // *** Start programmer edit section *** (Адрес.КодАдреса Get end)

                // *** End programmer edit section *** (Адрес.КодАдреса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.КодАдреса Set start)

                // *** End programmer edit section *** (Адрес.КодАдреса Set start)
                this.fКодАдреса = value;
                // *** Start programmer edit section *** (Адрес.КодАдреса Set end)

                // *** End programmer edit section *** (Адрес.КодАдреса Set end)
            }
        }
        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Адрес.КодКлиента CustomAttributes)
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.КодКлиента Get start)

                // *** End programmer edit section *** (Адрес.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Адрес.КодКлиента Get end)

                // *** End programmer edit section *** (Адрес.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.КодКлиента Set start)

                // *** End programmer edit section *** (Адрес.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Адрес.КодКлиента Set end)

                // *** End programmer edit section *** (Адрес.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// Улица.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.Улица CustomAttributes)

        // *** End programmer edit section *** (Адрес.Улица CustomAttributes)
        [StrLen(255)]
        public virtual string Улица
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.Улица Get start)

                // *** End programmer edit section *** (Адрес.Улица Get start)
                string result = this.fУлица;
                // *** Start programmer edit section *** (Адрес.Улица Get end)

                // *** End programmer edit section *** (Адрес.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.Улица Set start)

                // *** End programmer edit section *** (Адрес.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (Адрес.Улица Set end)

                // *** End programmer edit section *** (Адрес.Улица Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АдресE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресE", typeof(IIS.Internet_magazin.Адрес));
                }
            }
            
            /// <summary>
            /// "АдресL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресL", typeof(IIS.Internet_magazin.Адрес));
                }
            }
        }
    }
}
