//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Internet_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказы.
    /// </summary>
    // *** Start programmer edit section *** (Заказы CustomAttributes)

    // *** End programmer edit section *** (Заказы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказыE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "ДатаЗаказа as \'Дата заказа\'",
            "Время as \'Время\'",
            "Вобработке as \'Вобработке\'",
            "Завершен as \'Завершен\'",
            "КодКлиента as \'Код клиента\'",
            "Сумма as \'Сумма\'"})]
    [View("ЗаказыL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "ДатаЗаказа as \'Дата заказа\'",
            "Время as \'Время\'",
            "Вобработке as \'Вобработке\'",
            "Завершен as \'Завершен\'",
            "КодКлиента as \'Код клиента\'",
            "Сумма as \'Сумма\'"})]
    public class Заказы : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаказа;
        
        private int fКодЗаказа;
        
        private int fКодКлиента;
        
        private byte fВобработке;
        
        private string fВремя;
        
        private byte fЗавершен;
        
        private double fСумма;
        
        private int fКодАдреса;
        
        private IIS.Internet_magazin.Адрес fАдрес;
        
        private IIS.Internet_magazin.Клиент fКлиент;
        
        private IIS.Internet_magazin.DetailArrayOfКорзина fКорзина;
        
        private IIS.Internet_magazin.DetailArrayOfТовар fТовар;
        
        // *** Start programmer edit section *** (Заказы CustomMembers)

        // *** End programmer edit section *** (Заказы CustomMembers)

        
        /// <summary>
        /// Вобработке.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Вобработке CustomAttributes)

        // *** End programmer edit section *** (Заказы.Вобработке CustomAttributes)
        public virtual byte Вобработке
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Вобработке Get start)

                // *** End programmer edit section *** (Заказы.Вобработке Get start)
                byte result = this.fВобработке;
                // *** Start programmer edit section *** (Заказы.Вобработке Get end)

                // *** End programmer edit section *** (Заказы.Вобработке Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Вобработке Set start)

                // *** End programmer edit section *** (Заказы.Вобработке Set start)
                this.fВобработке = value;
                // *** Start programmer edit section *** (Заказы.Вобработке Set end)

                // *** End programmer edit section *** (Заказы.Вобработке Set end)
            }
        }
        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Время CustomAttributes)

        // *** End programmer edit section *** (Заказы.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Время Get start)

                // *** End programmer edit section *** (Заказы.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Заказы.Время Get end)

                // *** End programmer edit section *** (Заказы.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Время Set start)

                // *** End programmer edit section *** (Заказы.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Заказы.Время Set end)

                // *** End programmer edit section *** (Заказы.Время Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ДатаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.ДатаЗаказа CustomAttributes)
        public virtual System.DateTime ДатаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ДатаЗаказа Get start)

                // *** End programmer edit section *** (Заказы.ДатаЗаказа Get start)
                System.DateTime result = this.fДатаЗаказа;
                // *** Start programmer edit section *** (Заказы.ДатаЗаказа Get end)

                // *** End programmer edit section *** (Заказы.ДатаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ДатаЗаказа Set start)

                // *** End programmer edit section *** (Заказы.ДатаЗаказа Set start)
                this.fДатаЗаказа = value;
                // *** Start programmer edit section *** (Заказы.ДатаЗаказа Set end)

                // *** End programmer edit section *** (Заказы.ДатаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Завершен.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Завершен CustomAttributes)

        // *** End programmer edit section *** (Заказы.Завершен CustomAttributes)
        public virtual byte Завершен
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Завершен Get start)

                // *** End programmer edit section *** (Заказы.Завершен Get start)
                byte result = this.fЗавершен;
                // *** Start programmer edit section *** (Заказы.Завершен Get end)

                // *** End programmer edit section *** (Заказы.Завершен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Завершен Set start)

                // *** End programmer edit section *** (Заказы.Завершен Set start)
                this.fЗавершен = value;
                // *** Start programmer edit section *** (Заказы.Завершен Set end)

                // *** End programmer edit section *** (Заказы.Завершен Set end)
            }
        }
        
        /// <summary>
        /// КодАдреса.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодАдреса CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодАдреса CustomAttributes)
        public virtual int КодАдреса
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодАдреса Get start)

                // *** End programmer edit section *** (Заказы.КодАдреса Get start)
                int result = this.fКодАдреса;
                // *** Start programmer edit section *** (Заказы.КодАдреса Get end)

                // *** End programmer edit section *** (Заказы.КодАдреса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодАдреса Set start)

                // *** End programmer edit section *** (Заказы.КодАдреса Set start)
                this.fКодАдреса = value;
                // *** Start programmer edit section *** (Заказы.КодАдреса Set end)

                // *** End programmer edit section *** (Заказы.КодАдреса Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодКлиента CustomAttributes)
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодКлиента Get start)

                // *** End programmer edit section *** (Заказы.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Заказы.КодКлиента Get end)

                // *** End programmer edit section *** (Заказы.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодКлиента Set start)

                // *** End programmer edit section *** (Заказы.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Заказы.КодКлиента Set end)

                // *** End programmer edit section *** (Заказы.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Сумма CustomAttributes)

        // *** End programmer edit section *** (Заказы.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Сумма Get start)

                // *** End programmer edit section *** (Заказы.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Заказы.Сумма Get end)

                // *** End programmer edit section *** (Заказы.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Сумма Set start)

                // *** End programmer edit section *** (Заказы.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Заказы.Сумма Set end)

                // *** End programmer edit section *** (Заказы.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Адрес CustomAttributes)

        // *** End programmer edit section *** (Заказы.Адрес CustomAttributes)
        [PropertyStorage(new string[] {
                "Адрес"})]
        [NotNull()]
        public virtual IIS.Internet_magazin.Адрес Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Адрес Get start)

                // *** End programmer edit section *** (Заказы.Адрес Get start)
                IIS.Internet_magazin.Адрес result = this.fАдрес;
                // *** Start programmer edit section *** (Заказы.Адрес Get end)

                // *** End programmer edit section *** (Заказы.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Адрес Set start)

                // *** End programmer edit section *** (Заказы.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Заказы.Адрес Set end)

                // *** End programmer edit section *** (Заказы.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказы.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Internet_magazin.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Клиент Get start)

                // *** End programmer edit section *** (Заказы.Клиент Get start)
                IIS.Internet_magazin.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказы.Клиент Get end)

                // *** End programmer edit section *** (Заказы.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Клиент Set start)

                // *** End programmer edit section *** (Заказы.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказы.Клиент Set end)

                // *** End programmer edit section *** (Заказы.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Корзина CustomAttributes)

        // *** End programmer edit section *** (Заказы.Корзина CustomAttributes)
        public virtual IIS.Internet_magazin.DetailArrayOfКорзина Корзина
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Корзина Get start)

                // *** End programmer edit section *** (Заказы.Корзина Get start)
                if ((this.fКорзина == null))
                {
                    this.fКорзина = new IIS.Internet_magazin.DetailArrayOfКорзина(this);
                }
                IIS.Internet_magazin.DetailArrayOfКорзина result = this.fКорзина;
                // *** Start programmer edit section *** (Заказы.Корзина Get end)

                // *** End programmer edit section *** (Заказы.Корзина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Корзина Set start)

                // *** End programmer edit section *** (Заказы.Корзина Set start)
                this.fКорзина = value;
                // *** Start programmer edit section *** (Заказы.Корзина Set end)

                // *** End programmer edit section *** (Заказы.Корзина Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Товар CustomAttributes)

        // *** End programmer edit section *** (Заказы.Товар CustomAttributes)
        public virtual IIS.Internet_magazin.DetailArrayOfТовар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Товар Get start)

                // *** End programmer edit section *** (Заказы.Товар Get start)
                if ((this.fТовар == null))
                {
                    this.fТовар = new IIS.Internet_magazin.DetailArrayOfТовар(this);
                }
                IIS.Internet_magazin.DetailArrayOfТовар result = this.fТовар;
                // *** Start programmer edit section *** (Заказы.Товар Get end)

                // *** End programmer edit section *** (Заказы.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Товар Set start)

                // *** End programmer edit section *** (Заказы.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Заказы.Товар Set end)

                // *** End programmer edit section *** (Заказы.Товар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыE", typeof(IIS.Internet_magazin.Заказы));
                }
            }
            
            /// <summary>
            /// "ЗаказыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыL", typeof(IIS.Internet_magazin.Заказы));
                }
            }
        }
    }
}
