//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Internet_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Категория.
    /// </summary>
    // *** Start programmer edit section *** (Категория CustomAttributes)

    // *** End programmer edit section *** (Категория CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КатегорияE", new string[] {
            "Название as \'Название\'",
            "КодКатегории as \'Код категории\'"})]
    [View("КатегорияL", new string[] {
            "Название as \'Название\'",
            "КодКатегории as \'Код категории\'"})]
    public class Категория : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private int fКодКатегории;
        
        // *** Start programmer edit section *** (Категория CustomMembers)

        // *** End programmer edit section *** (Категория CustomMembers)

        
        /// <summary>
        /// КодКатегории.
        /// </summary>
        // *** Start programmer edit section *** (Категория.КодКатегории CustomAttributes)

        // *** End programmer edit section *** (Категория.КодКатегории CustomAttributes)
        public virtual int КодКатегории
        {
            get
            {
                // *** Start programmer edit section *** (Категория.КодКатегории Get start)

                // *** End programmer edit section *** (Категория.КодКатегории Get start)
                int result = this.fКодКатегории;
                // *** Start programmer edit section *** (Категория.КодКатегории Get end)

                // *** End programmer edit section *** (Категория.КодКатегории Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Категория.КодКатегории Set start)

                // *** End programmer edit section *** (Категория.КодКатегории Set start)
                this.fКодКатегории = value;
                // *** Start programmer edit section *** (Категория.КодКатегории Set end)

                // *** End programmer edit section *** (Категория.КодКатегории Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Категория.Название CustomAttributes)

        // *** End programmer edit section *** (Категория.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Категория.Название Get start)

                // *** End programmer edit section *** (Категория.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Категория.Название Get end)

                // *** End programmer edit section *** (Категория.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Категория.Название Set start)

                // *** End programmer edit section *** (Категория.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Категория.Название Set end)

                // *** End programmer edit section *** (Категория.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КатегорияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КатегорияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КатегорияE", typeof(IIS.Internet_magazin.Категория));
                }
            }
            
            /// <summary>
            /// "КатегорияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КатегорияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КатегорияL", typeof(IIS.Internet_magazin.Категория));
                }
            }
        }
    }
}
