//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Internet_magazin
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Корзина.
    /// </summary>
    // *** Start programmer edit section *** (Корзина CustomAttributes)

    // *** End programmer edit section *** (Корзина CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КорзинаE", new string[] {
            "Количество as \'Количество\'",
            "КодКорзины as \'Код корзины\'",
            "КодТовара as \'Код товара\'",
            "КодЗаказа as \'Код заказа\'"})]
    public class Корзина : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private int fКодКорзины;
        
        private int fКодТовара;
        
        private int fКодЗаказа;
        
        private IIS.Internet_magazin.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (Корзина CustomMembers)

        // *** End programmer edit section *** (Корзина CustomMembers)

        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Корзина.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Корзина.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Корзина.КодЗаказа Get start)

                // *** End programmer edit section *** (Корзина.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Корзина.КодЗаказа Get end)

                // *** End programmer edit section *** (Корзина.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корзина.КодЗаказа Set start)

                // *** End programmer edit section *** (Корзина.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Корзина.КодЗаказа Set end)

                // *** End programmer edit section *** (Корзина.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// КодКорзины.
        /// </summary>
        // *** Start programmer edit section *** (Корзина.КодКорзины CustomAttributes)

        // *** End programmer edit section *** (Корзина.КодКорзины CustomAttributes)
        public virtual int КодКорзины
        {
            get
            {
                // *** Start programmer edit section *** (Корзина.КодКорзины Get start)

                // *** End programmer edit section *** (Корзина.КодКорзины Get start)
                int result = this.fКодКорзины;
                // *** Start programmer edit section *** (Корзина.КодКорзины Get end)

                // *** End programmer edit section *** (Корзина.КодКорзины Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корзина.КодКорзины Set start)

                // *** End programmer edit section *** (Корзина.КодКорзины Set start)
                this.fКодКорзины = value;
                // *** Start programmer edit section *** (Корзина.КодКорзины Set end)

                // *** End programmer edit section *** (Корзина.КодКорзины Set end)
            }
        }
        
        /// <summary>
        /// КодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Корзина.КодТовара CustomAttributes)

        // *** End programmer edit section *** (Корзина.КодТовара CustomAttributes)
        public virtual int КодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Корзина.КодТовара Get start)

                // *** End programmer edit section *** (Корзина.КодТовара Get start)
                int result = this.fКодТовара;
                // *** Start programmer edit section *** (Корзина.КодТовара Get end)

                // *** End programmer edit section *** (Корзина.КодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корзина.КодТовара Set start)

                // *** End programmer edit section *** (Корзина.КодТовара Set start)
                this.fКодТовара = value;
                // *** Start programmer edit section *** (Корзина.КодТовара Set end)

                // *** End programmer edit section *** (Корзина.КодТовара Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Корзина.Количество CustomAttributes)

        // *** End programmer edit section *** (Корзина.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Корзина.Количество Get start)

                // *** End programmer edit section *** (Корзина.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Корзина.Количество Get end)

                // *** End programmer edit section *** (Корзина.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корзина.Количество Set start)

                // *** End programmer edit section *** (Корзина.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Корзина.Количество Set end)

                // *** End programmer edit section *** (Корзина.Количество Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Internet_magazin.Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Корзина.Заказы CustomAttributes)

        // *** End programmer edit section *** (Корзина.Заказы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказы"})]
        public virtual IIS.Internet_magazin.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (Корзина.Заказы Get start)

                // *** End programmer edit section *** (Корзина.Заказы Get start)
                IIS.Internet_magazin.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (Корзина.Заказы Get end)

                // *** End programmer edit section *** (Корзина.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корзина.Заказы Set start)

                // *** End programmer edit section *** (Корзина.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (Корзина.Заказы Set end)

                // *** End programmer edit section *** (Корзина.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КорзинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КорзинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КорзинаE", typeof(IIS.Internet_magazin.Корзина));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Корзина.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКорзина CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКорзина CustomAttributes)
    public class DetailArrayOfКорзина : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Internet_magazin.DetailArrayOfКорзина members)

        // *** End programmer edit section *** (IIS.Internet_magazin.DetailArrayOfКорзина members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Корзина by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Корзина.
        /// </summary>
        public DetailArrayOfКорзина(IIS.Internet_magazin.Заказы fЗаказы) : 
                base(typeof(Корзина), ((ICSSoft.STORMNET.DataObject)(fЗаказы)))
        {
        }
        
        public IIS.Internet_magazin.Корзина this[int index]
        {
            get
            {
                return ((IIS.Internet_magazin.Корзина)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Internet_magazin.Корзина dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
